In [1]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU Found")


True
NVIDIA GeForce GTX 1650


In [ ]:
# moving an existng tensor to GPU
a = torch.rand(2,3)
print(a)
device = torch.device('cuda')
a.to(device=device)

tensor([[0.7017, 0.1680, 0.9220],
        [0.0461, 0.0154, 0.0175]])


tensor([[0.7017, 0.1680, 0.9220],
        [0.0461, 0.0154, 0.0175]], device='cuda:0')

In [7]:
a+5

tensor([[5.7017, 5.1680, 5.9220],
        [5.0461, 5.0154, 5.0175]])

In [8]:
# Why we use GPU as compare to CPU
import time

# Define the size of matrices
size = 10000

matrix_cpu1 = torch.rand(size,size)
matrix_cpu2 = torch.rand(size,size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time = time.time()-start_time

print(f"Time on CPU:{cpu_time:.4f} second")


Time on CPU:6.5121 second


In [9]:
# Move matrix to GPU
matrix_gpu1 = matrix_cpu1.to(device=device)
matrix_gpu2 = matrix_cpu2.to(device=device)

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1,matrix_gpu2)
gpu_time = time.time()-start_time

print(f"Time on GPU:{gpu_time:.4f} second")

# Compare result
print("\nSpeedup (CPU Time / GPU Time):",cpu_time/gpu_time)


Time on GPU:0.1073 second

Speedup (CPU Time / GPU Time): 60.68369462100897


In [11]:
b=torch.rand(2,3,4)
print(b)

tensor([[[0.7509, 0.3636, 0.8172, 0.0276],
         [0.7985, 0.5709, 0.8268, 0.0812],
         [0.1764, 0.8808, 0.9590, 0.4947]],

        [[0.3057, 0.0946, 0.4351, 0.8106],
         [0.8536, 0.1258, 0.6018, 0.0108],
         [0.7988, 0.1521, 0.0627, 0.0216]]])


In [12]:
b.reshape(2,4,3)

tensor([[[0.7509, 0.3636, 0.8172],
         [0.0276, 0.7985, 0.5709],
         [0.8268, 0.0812, 0.1764],
         [0.8808, 0.9590, 0.4947]],

        [[0.3057, 0.0946, 0.4351],
         [0.8106, 0.8536, 0.1258],
         [0.6018, 0.0108, 0.7988],
         [0.1521, 0.0627, 0.0216]]])

In [ ]:
# permute
b.permute(2,0,1)

tensor([[[0.7509, 0.7985, 0.1764],
         [0.3057, 0.8536, 0.7988]],

        [[0.3636, 0.5709, 0.8808],
         [0.0946, 0.1258, 0.1521]],

        [[0.8172, 0.8268, 0.9590],
         [0.4351, 0.6018, 0.0627]],

        [[0.0276, 0.0812, 0.4947],
         [0.8106, 0.0108, 0.0216]]])

In [19]:
# unsqueeze
# image size
c=torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])