In [1]:
import torch
# using empty
a=torch.empty(2,3)
print(a)

# using check type
print(type(a))


tensor([[2.3822e-44, 0.0000e+00, 1.5893e-39],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
<class 'torch.Tensor'>


In [11]:
# Using zeros and ones
using_zero=torch.zeros(2,3)
using_ones = torch.ones(3,3)
print(using_zero)
print(using_ones)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [12]:
# using rand 
a = torch.rand(2,4)
print(a)

tensor([[0.8992, 0.4693, 0.8280, 0.3693],
        [0.0338, 0.3517, 0.0621, 0.2938]])


In [15]:
# Use of seed and manual seed
torch.manual_seed(100)
a= torch.rand(2,2)
print(a)
print(type(a))


tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])
<class 'torch.Tensor'>


In [26]:
# use of full and eye
a=torch.eye(5)
print(a)
print(torch.full((3,3),10))


tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])


In [29]:
print(a.device)

cpu


In [30]:
# custom tensor
a = torch.tensor([1,2,3,4,5])
print(a)

tensor([1, 2, 3, 4, 5])


In [31]:
# use of arange and linspace
a = torch.arange(1,10)
print(a)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [32]:
a= torch.linspace(10,20,50)
print(a)

tensor([10.0000, 10.2041, 10.4082, 10.6122, 10.8163, 11.0204, 11.2245, 11.4286,
        11.6327, 11.8367, 12.0408, 12.2449, 12.4490, 12.6531, 12.8571, 13.0612,
        13.2653, 13.4694, 13.6735, 13.8776, 14.0816, 14.2857, 14.4898, 14.6939,
        14.8980, 15.1020, 15.3061, 15.5102, 15.7143, 15.9184, 16.1224, 16.3265,
        16.5306, 16.7347, 16.9388, 17.1429, 17.3469, 17.5510, 17.7551, 17.9592,
        18.1633, 18.3673, 18.5714, 18.7755, 18.9796, 19.1837, 19.3878, 19.5918,
        19.7959, 20.0000])


In [34]:
# Tensor shapes
# We can find out the shapes of tensor using shape attribute of torch
a = torch.arange(1,10)
print(a)
print(a.shape)

b= torch.tensor([[2,4,6],[3,2,1],[4,2,5]])
print(b)
print(b.shape)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])
tensor([[2, 4, 6],
        [3, 2, 1],
        [4, 2, 5]])
torch.Size([3, 3])


In [37]:
# use of empty
p = torch.empty_like(b)
print(p)

tensor([[126582679210960, 107191297705072, 107191297642368],
        [107191221723600,               0, 107191297828944],
        [107191270157104, 126581895573856,               1]])


In [42]:
q= torch.full((3,3),2)
print(q)
q= torch.eye(2)
print(q)

q.dtype

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])
tensor([[1., 0.],
        [0., 1.]])


torch.float32

In [44]:
# assign dataype
a= torch.tensor([1.0,2.0,3.0],dtype= torch.int32)
print(a)
a= torch.tensor([1 ,2 ,3],dtype= torch.float64)
print(a)


tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.], dtype=torch.float64)


In [45]:
# Mathematical Operation
# Scaler Operation
x=torch.rand(3,3)
print(x)



tensor([[0.6765, 0.7539, 0.2627],
        [0.0428, 0.2080, 0.1180],
        [0.1217, 0.7356, 0.7118]])


In [52]:
# Addition
x=x+10
print(x)

# Subtraction
x=x-4
print(x)

# Multiplication
x=x*4
print(x)

# Division
x=x//2
print(x)

# Mod 
x=x%3
print(x)

# pow
x= x**4
print(x)

# clamp 
a = torch.clamp(x,5,15)
print(a)


tensor([[26., 10., 11.],
        [10., 10., 10.],
        [10., 26., 26.]])
tensor([[22.,  6.,  7.],
        [ 6.,  6.,  6.],
        [ 6., 22., 22.]])
tensor([[88., 24., 28.],
        [24., 24., 24.],
        [24., 88., 88.]])
tensor([[44., 12., 14.],
        [12., 12., 12.],
        [12., 44., 44.]])
tensor([[2., 0., 2.],
        [0., 0., 0.],
        [0., 2., 2.]])
tensor([[16.,  0., 16.],
        [ 0.,  0.,  0.],
        [ 0., 16., 16.]])
tensor([[15.,  5., 15.],
        [ 5.,  5.,  5.],
        [ 5., 15., 15.]])


In [16]:
# Reduction Operation

e= torch.randint(size=(2,3),low=0,high=10,dtype = torch.float32)
print(e)


tensor([[1., 3., 2.],
        [3., 8., 8.]])


In [29]:
# sum
print(torch.sum(e))

# sum along column
print(torch.sum(e,axis=0))

# sum along row
print(torch.sum(e,axis=1))

# mean
print(torch.mean(e))

# mean along col
print(torch.mean(e,axis = 0))

# mean along row
print(torch.mean(e,axis = 1))

# max and min
print("Max:\n",torch.max(e),"\nMin :\n",torch.min(e))

# product
print("Product:\n",torch.prod(e))

# standard deviation
print("Standard Deviation:\n",torch.std(e))

# Varience
print("Variance :\n",torch.var(e))

# Argmax(position of max element) and argmin(position of argmin)
print("Argmax: \n",torch.argmax(e),"\n Argmin :\n",torch.argmin(e))

tensor(25.)
tensor([ 4., 11., 10.])
tensor([ 6., 19.])
tensor(4.1667)
tensor([2.0000, 5.5000, 5.0000])
tensor([2.0000, 6.3333])
Max:
 tensor(8.) 
Min :
 tensor(1.)
Product:
 tensor(1152.)
Standard Deviation:
 tensor(3.0605)
Variance :
 tensor(9.3667)
Argmax: 
 tensor(4) 
 Argmin :
 tensor(0)


In [51]:
# Matrix Operation
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)

print("Matrix:\n",f,"\nMatrix\n",g)


Matrix:
 tensor([[8, 9, 6],
        [4, 9, 0]]) 
Matrix
 tensor([[4, 6],
        [4, 5],
        [7, 6]])


In [48]:
# matrix mul
print("Matrix Multiplication\n",torch.matmul(f,g))

# f= torch.tensor([1,2,4])
# g = torch.tensor([3,2,5])
# # dot product
# print("Dot Product:",torch.dot(f,g))



Matrix Multiplication
 tensor(27)


In [52]:
# Transpose
torch.transpose(f,0,1)

tensor([[8, 4],
        [9, 9],
        [6, 0]])

In [56]:
a=torch.tensor([1,2,3])
b=torch.tensor([2,4,3])
# print(a+b)
print(a)
a.add_(b) 
print(a)


tensor([1, 2, 3])
tensor([3, 6, 6])


In [2]:
# Tensor operation on GPU
torch.cuda.is_available()

/home/dheeraj/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages/torch/cuda/__init__.py:182: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0


False

In [3]:
!nvidia-smi


Thu Aug 14 17:14:24 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.169                Driver Version: 570.169        CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650        Off |   00000000:01:00.0 Off |                  N/A |
| N/A   44C    P8              1W /   50W |       5MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
import torch
print(torch.version.cuda)

12.8


In [5]:
print(torch.cuda.is_available())


False
