In [1]:
import torch
import torch.nn as nn

In [2]:
class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out
    


In [3]:
# create a dataset
features = torch.rand(10,5)

# Create Model
model = Model(features.shape[1])

# call the model forward pass
model(features)

tensor([[0.6847],
        [0.6071],
        [0.6115],
        [0.5508],
        [0.6045],
        [0.5124],
        [0.6709],
        [0.6274],
        [0.5532],
        [0.5083]], grad_fn=<SigmoidBackward0>)

In [4]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.4132, -0.3285, -0.3537,  0.0382,  0.1837]], requires_grad=True)

In [5]:
model.linear.bias


Parameter containing:
tensor([0.3617], requires_grad=True)

In [76]:
from torchinfo import summary

model_summary = summary(model, input_size =(10,5))
model_summary

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [84]:
# Neural Network with Hidden Layer
class Advanced_Model(nn.Module):
    def __init__(self,num_feautures):
        super().__init__()
        # creating a container
        self.network = nn.Sequential(
            nn.Linear(num_feautures,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

        # self.linear1 =nn.Linear(num_feautures,3)
        # self.reLU = nn.ReLU()
        # self.linear2 = nn.Linear(3,1)
        # self.sigmoid = nn.Sigmoid()
    
    def forward(self,features):
        out = self.network(features)
        # out = self.reLU(out)
        # out = self.linear2(out)
        # out = self.sigmoid(out)
        return out


In [85]:
# create a dataset
features = torch.rand(10,5)

# Create Model
model = Advanced_Model(features.shape[1])

# call the model forward pass
model(features)

tensor([[0.4425],
        [0.4198],
        [0.4212],
        [0.4346],
        [0.4409],
        [0.4068],
        [0.4051],
        [0.3967],
        [0.4446],
        [0.4223]], grad_fn=<SigmoidBackward0>)

In [87]:
model.network


Sequential(
  (0): Linear(in_features=5, out_features=3, bias=True)
  (1): ReLU()
  (2): Linear(in_features=3, out_features=1, bias=True)
  (3): Sigmoid()
)

In [88]:
from torchinfo import summary

model_summary = summary(model, input_size =(10,5))
model_summary

Layer (type:depth-idx)                   Output Shape              Param #
Advanced_Model                           [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [38]:
# Working with the breast cancer csv file
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [39]:
df = pd.read_csv('breast-cancer.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [40]:
df.shape
# Remove the unnescessary column 
df.drop(columns=['id'],inplace = True)

In [71]:
# Train Test Split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size = 0.3,random_state = 50)


In [72]:
scaler = StandardScaler()
X_train = scaler.fit_transform(x_train)
X_test = scaler.transform(x_test)

In [73]:
X_train

array([[ 1.54861552,  0.20960295,  1.49941338, ...,  0.67863262,
        -0.54878028,  0.40334162],
       [-0.65449122, -0.44049871, -0.68138332, ..., -0.36526984,
         0.35036679, -0.74592294],
       [ 2.05828947,  0.37909374,  2.16603246, ...,  1.019133  ,
        -0.08617563,  0.25327326],
       ...,
       [-0.78601998, -0.10848251, -0.81510393, ..., -0.80388809,
         0.62076247, -0.75294053],
       [-0.79424052,  0.44178211, -0.80280322, ..., -0.49400288,
        -0.09269119,  0.23923809],
       [-0.56954556, -0.30815659, -0.57226413, ..., -0.88050067,
        -0.7817115 , -0.35617704]])

In [74]:
X_test

array([[-0.32566931, -0.17813626, -0.30244212, ...,  0.14846757,
         0.36991347, -0.03876626],
       [-1.11758206,  0.05404291, -1.11032095, ..., -1.39692624,
        -1.0162716 , -0.88897372],
       [ 0.54844891, -0.13634401,  0.63836374, ...,  0.85634992,
        -0.18879567,  1.20982413],
       ...,
       [-0.15851818, -0.97683258, -0.17626065, ..., -0.15619066,
         0.81622922,  0.67432838],
       [-0.48734008, -1.51548824, -0.55083708, ..., -1.3300209 ,
        -0.98695159, -0.73458684],
       [-0.6572314 , -0.15259655, -0.58654882, ...,  0.5785733 ,
         3.05432356,  3.03979447]])

In [75]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [76]:
y_train

array([1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,

In [45]:
y_test

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0])

In [77]:
x_train_tensor = torch.from_numpy(X_train.astype(np.float32))
x_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [78]:
x_train_tensor.shape
x_train_tensor

tensor([[ 1.5486,  0.2096,  1.4994,  ...,  0.6786, -0.5488,  0.4033],
        [-0.6545, -0.4405, -0.6814,  ..., -0.3653,  0.3504, -0.7459],
        [ 2.0583,  0.3791,  2.1660,  ...,  1.0191, -0.0862,  0.2533],
        ...,
        [-0.7860, -0.1085, -0.8151,  ..., -0.8039,  0.6208, -0.7529],
        [-0.7942,  0.4418, -0.8028,  ..., -0.4940, -0.0927,  0.2392],
        [-0.5695, -0.3082, -0.5723,  ..., -0.8805, -0.7817, -0.3562]])

In [79]:
y_train_tensor.shape

torch.Size([398])

In [80]:
import torch.nn as nn
# Defining the model
class SimpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        # self.network = nn.Sequential(

        # )
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self,features):
            out = self.linear(features)
            out = self.sigmoid(out)
            return out
    # def loss_function(self,y_pred,y):
    #     epsilon = 1e-7
    #     y_pred = torch.clamp(y_pred,epsilon, 1 - epsilon)

    #     # calculate loss using cross-entrophy
    #     loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    #     return loss

    

In [81]:
learning_rate = 0.2
epochs = 25


In [83]:
loss_function =nn.BCELoss()

In [60]:
# # define optimizer
# optimizer = torch.optim.SGD()

In [84]:
model = SimpleNN(x_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)
for epoch in range(epochs):

    # forward pass
    y_pred = model(x_train_tensor)

    # loss calculation
    loss = loss_function(y_pred,y_train_tensor.reshape(-1,1))

    # backward pass
    loss.backward()

    # # parameters update
    # with torch.no_grad():
    #     model.linear.weight -= learning_rate * model.linear.weight.grad
    #     model.linear.bias -= learning_rate * model.linear.bias.grad
    
    # # zero gradients
    # model.linear.weight.grad.zero_()
    # model.linear.bias.grad.zero_()
    
    # parameter update
    optimizer.step()
    optimizer.zero_grad()


    # print loss in each epoch
    print(f"Epoch :{epoch+1} , Loss: {loss.item()}")


Epoch :1 , Loss: 0.5639873743057251
Epoch :2 , Loss: 0.3937027156352997
Epoch :3 , Loss: 0.32538577914237976
Epoch :4 , Loss: 0.2847072184085846
Epoch :5 , Loss: 0.25669798254966736
Epoch :6 , Loss: 0.23583289980888367
Epoch :7 , Loss: 0.21949346363544464
Epoch :8 , Loss: 0.20624741911888123
Epoch :9 , Loss: 0.19523344933986664
Epoch :10 , Loss: 0.18589679896831512
Epoch :11 , Loss: 0.1778610795736313
Epoch :12 , Loss: 0.170860156416893
Epoch :13 , Loss: 0.16469906270503998
Epoch :14 , Loss: 0.15923090279102325
Epoch :15 , Loss: 0.1543421745300293
Epoch :16 , Loss: 0.14994332194328308
Epoch :17 , Loss: 0.14596252143383026
Epoch :18 , Loss: 0.14234130084514618
Epoch :19 , Loss: 0.13903145492076874
Epoch :20 , Loss: 0.13599300384521484
Epoch :21 , Loss: 0.13319242000579834
Epoch :22 , Loss: 0.1306014358997345
Epoch :23 , Loss: 0.12819600105285645
Epoch :24 , Loss: 0.125955730676651
Epoch :25 , Loss: 0.12386299669742584


In [86]:
# model evaluation
with torch.no_grad():
    y_pred = model.forward(x_test_tensor)
    y_pred  = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy : {accuracy.item()}")

Accuracy : 0.5715946555137634
