In [69]:
import torch
import torch.nn as nn

In [70]:
class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out
    


In [71]:
# create a dataset
features = torch.rand(10,5)

# Create Model
model = Model(features.shape[1])

# call the model forward pass
model(features)

tensor([[0.5477],
        [0.5791],
        [0.6305],
        [0.5543],
        [0.5986],
        [0.6132],
        [0.5742],
        [0.6216],
        [0.5713],
        [0.5244]], grad_fn=<SigmoidBackward0>)

In [72]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[-0.1106, -0.2080,  0.4216,  0.0642, -0.3451]], requires_grad=True)

In [ ]:
model.linear.bias


Parameter containing:
tensor([0.3590], requires_grad=True)

In [76]:
from torchinfo import summary

model_summary = summary(model, input_size =(10,5))
model_summary

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [84]:
# Neural Network with Hidden Layer
class Advanced_Model(nn.Module):
    def __init__(self,num_feautures):
        super().__init__()
        # creating a container
        self.network = nn.Sequential(
            nn.Linear(num_feautures,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

        # self.linear1 =nn.Linear(num_feautures,3)
        # self.reLU = nn.ReLU()
        # self.linear2 = nn.Linear(3,1)
        # self.sigmoid = nn.Sigmoid()
    
    def forward(self,features):
        out = self.network(features)
        # out = self.reLU(out)
        # out = self.linear2(out)
        # out = self.sigmoid(out)
        return out


In [85]:
# create a dataset
features = torch.rand(10,5)

# Create Model
model = Advanced_Model(features.shape[1])

# call the model forward pass
model(features)

tensor([[0.4425],
        [0.4198],
        [0.4212],
        [0.4346],
        [0.4409],
        [0.4068],
        [0.4051],
        [0.3967],
        [0.4446],
        [0.4223]], grad_fn=<SigmoidBackward0>)

In [87]:
model.network


Sequential(
  (0): Linear(in_features=5, out_features=3, bias=True)
  (1): ReLU()
  (2): Linear(in_features=3, out_features=1, bias=True)
  (3): Sigmoid()
)

In [88]:
from torchinfo import summary

model_summary = summary(model, input_size =(10,5))
model_summary

Layer (type:depth-idx)                   Output Shape              Param #
Advanced_Model                           [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [105]:
# Working with the breast cancer csv file
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [106]:
df = pd.read_csv('breast-cancer.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [107]:
df.shape
# Remove the unnescessary column 
df.drop(columns=['id'],inplace = True)

In [108]:
# Train Test Split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size = 0.3,random_state = 19)


In [109]:
scaler = StandardScaler()
X_train = scaler.fit_transform(x_train)
X_test = scaler.transform(x_test)

In [110]:
X_train

array([[ 1.79425731,  0.09221347,  1.80388116, ...,  1.56645559,
         0.1557361 , -0.21827903],
       [-0.61143809, -1.0368692 , -0.55073179, ..., -0.81968672,
        -0.31471993,  0.99611375],
       [ 0.62918019, -0.70899653,  0.64116153, ...,  0.16409505,
         0.34237603,  0.25206565],
       ...,
       [-0.14656941, -1.48480793, -0.23024398, ..., -1.40253331,
        -1.02426017, -1.21902372],
       [-0.1349477 , -1.10382911, -0.15540712, ...,  0.22037199,
         0.07089977, -0.65195278],
       [-0.83225071, -1.17078903, -0.8412003 , ..., -1.14213838,
        -0.54763423, -0.78003534]])

In [112]:
X_test

array([[-0.28312459, -0.16639034, -0.36046858, ..., -0.97619745,
        -1.45615423, -1.23124737],
       [ 1.68094557,  1.38061455,  1.66012673, ...,  0.89569529,
         0.57683281, -0.01100849],
       [ 0.07133778,  0.69485268,  0.22342808, ...,  0.9763082 ,
        -0.13424991,  1.50631815],
       ...,
       [-0.62015438,  0.55400597, -0.60485111, ..., -0.40780035,
        -0.96564598,  0.77927687],
       [-0.53008607,  0.31849179, -0.58836163, ..., -0.60842004,
        -0.36562173, -0.85444015],
       [-0.33542231,  0.5147536 , -0.35962297, ..., -0.88676275,
        -0.68337236, -0.17788785]])

In [113]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [97]:
y_train

array([1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,

In [114]:
y_test

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [115]:
x_train_tensor = torch.from_numpy(X_train)
x_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [100]:
x_train_tensor.shape
x_train_tensor

tensor([[ 1.7943,  0.0922,  1.8039,  ...,  1.5665,  0.1557, -0.2183],
        [-0.6114, -1.0369, -0.5507,  ..., -0.8197, -0.3147,  0.9961],
        [ 0.6292, -0.7090,  0.6412,  ...,  0.1641,  0.3424,  0.2521],
        ...,
        [-0.1466, -1.4848, -0.2302,  ..., -1.4025, -1.0243, -1.2190],
        [-0.1349, -1.1038, -0.1554,  ...,  0.2204,  0.0709, -0.6520],
        [-0.8323, -1.1708, -0.8412,  ..., -1.1421, -0.5476, -0.7800]],
       dtype=torch.float64)

In [116]:
y_train_tensor.shape

torch.Size([398])

In [117]:
import torch.nn as nn
# Defining the model
class SimpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        # self.network = nn.Sequential(

        # )
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self,features):
            out = self.linear(features)
            out = self.sigmoid(out)
            return out
    def loss_function(self,y_pred,y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,epsilon, 1 - epsilon)

        # calculate loss using cross-entrophy
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

    

In [118]:
learning_rate = 0.1
epochs = 25


In [ ]:
model = SimpleNN(x_train_tensor.shape[1])
for epoch in range(epochs):

    # forward pass
    y_pred = model(x_train_tensor)

    # loss calculation
    loss= model.loss_function(y_pred,y_train_tensor)

    # backward pass
    loss.backward()

    # parameters update
    with torch.no_grad():
        model.linear.weight -= learning_rate * model.linear.weight.grad
        model.linear.bias -= learning_rate * model.linear.bias.grad
    
    # zero gradients
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()

    # print loss in each epoch
    print(f"Epoch :{epoch+1} , Loss: {loss.item()}")


RuntimeError: mat1 and mat2 must have the same dtype, but got Double and Float