Import the library 

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

Load the dataset

In [2]:
df = pd.read_csv('breast-cancer.csv')
df.head()


id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

Find the shape and remove unnecessary column

In [3]:
df.shape
# Remove the unnescessary column 
df.drop(columns=['id'],inplace = True)

Create the training data and test data

In [4]:
# Train Test Split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size = 0.3,random_state = 19)


Scaling the Datset

In [5]:
scaler = StandardScaler()
X_train = scaler.fit_transform(x_train)
X_test = scaler.transform(x_test)

In [6]:
X_train

array([[ 1.79425731,  0.09221347,  1.80388116, ...,  1.56645559,
         0.1557361 , -0.21827903],
       [-0.61143809, -1.0368692 , -0.55073179, ..., -0.81968672,
        -0.31471993,  0.99611375],
       [ 0.62918019, -0.70899653,  0.64116153, ...,  0.16409505,
         0.34237603,  0.25206565],
       ...,
       [-0.14656941, -1.48480793, -0.23024398, ..., -1.40253331,
        -1.02426017, -1.21902372],
       [-0.1349477 , -1.10382911, -0.15540712, ...,  0.22037199,
         0.07089977, -0.65195278],
       [-0.83225071, -1.17078903, -0.8412003 , ..., -1.14213838,
        -0.54763423, -0.78003534]])

In [28]:
X_test

array([[-0.28312459, -0.16639034, -0.36046858, ..., -0.97619745,
        -1.45615423, -1.23124737],
       [ 1.68094557,  1.38061455,  1.66012673, ...,  0.89569529,
         0.57683281, -0.01100849],
       [ 0.07133778,  0.69485268,  0.22342808, ...,  0.9763082 ,
        -0.13424991,  1.50631815],
       ...,
       [-0.62015438,  0.55400597, -0.60485111, ..., -0.40780035,
        -0.96564598,  0.77927687],
       [-0.53008607,  0.31849179, -0.58836163, ..., -0.60842004,
        -0.36562173, -0.85444015],
       [-0.33542231,  0.5147536 , -0.35962297, ..., -0.88676275,
        -0.68337236, -0.17788785]])

Label Encoding

In [7]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [8]:
y_train

array([1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,

In [9]:
y_test

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0])

Numpy array to pytorch tensor

In [10]:
x_train_tensor = torch.from_numpy(X_train)
x_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [11]:
x_train_tensor.shape
x_train_tensor

tensor([[ 1.7943,  0.0922,  1.8039,  ...,  1.5665,  0.1557, -0.2183],
        [-0.6114, -1.0369, -0.5507,  ..., -0.8197, -0.3147,  0.9961],
        [ 0.6292, -0.7090,  0.6412,  ...,  0.1641,  0.3424,  0.2521],
        ...,
        [-0.1466, -1.4848, -0.2302,  ..., -1.4025, -1.0243, -1.2190],
        [-0.1349, -1.1038, -0.1554,  ...,  0.2204,  0.0709, -0.6520],
        [-0.8323, -1.1708, -0.8412,  ..., -1.1421, -0.5476, -0.7800]],
       dtype=torch.float64)

In [12]:
y_train_tensor.shape

torch.Size([398])

Defining the Model

In [13]:
class SimpleNN():
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1],1,dtype = torch.float64,requires_grad = True)
        self.bias = torch.zeros(1,dtype = torch.float64,requires_grad = True)
    
    def forward(self,X):
        z = torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self,y_pred,y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,epsilon, 1 - epsilon)

        # calculate loss using cross-entrophy
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss


Important Parameter which will require in Neural Network

In [14]:
learning_rate = 0.2
epochs = 25


Training Pipeline

In [15]:
# Create Model
model = SimpleNN(x_train_tensor)
# model.weights

# define loop
for epoch in range(epochs):
    # Forward Bias
    y_pred = model.forward(x_train_tensor)

    # loss calculate
    loss = model.loss_function(y_pred,y_train_tensor)
    print(f'Epoch: {epoch+1} loss:{loss.item()}')

    # backward pass
    loss.backward()

    # parameters update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad
    
    # Zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

Epoch: 1 loss:3.967864915692894
Epoch: 2 loss:3.74337607544363
Epoch: 3 loss:3.4925201847531366
Epoch: 4 loss:3.236021801539069
Epoch: 5 loss:2.9620618094062725
Epoch: 6 loss:2.6702660753222167
Epoch: 7 loss:2.364712752097398
Epoch: 8 loss:2.061022855409274
Epoch: 9 loss:1.7724236555117145
Epoch: 10 loss:1.5182434724404408
Epoch: 11 loss:1.3043798432779257
Epoch: 12 loss:1.1442588887387715
Epoch: 13 loss:1.0295953818918044
Epoch: 14 loss:0.953020120341448
Epoch: 15 loss:0.8994961524091599
Epoch: 16 loss:0.8589517516903582
Epoch: 17 loss:0.8265683995405672
Epoch: 18 loss:0.8001683704526772
Epoch: 19 loss:0.7785366335993995
Epoch: 20 loss:0.7608047256914916
Epoch: 21 loss:0.7462698031519854
Epoch: 22 loss:0.7343459603734915
Epoch: 23 loss:0.724547071571488
Epoch: 24 loss:0.7164739481988751
Epoch: 25 loss:0.7098011789960765


In [16]:
model.bias

tensor([-0.3485], dtype=torch.float64, requires_grad=True)

Model Evaluation

In [17]:
with torch.no_grad():
    y_pred = model.forward(x_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy : {accuracy.item()}")


Accuracy : 0.5874627828598022
