Import the library 

In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

Load the dataset

In [3]:
df = pd.read_csv('breast-cancer.csv')
df.head()


id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

Find the shape and remove unnecessary column

In [4]:
df.shape
# Remove the unnescessary column 
df.drop(columns=['id'],inplace = True)

Create the training data and test data

In [ ]:
# Train Test Split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size = 0.3,random_state = 19)


Scaling the Datset

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(x_train)
X_test = scaler.transform(x_test)

In [6]:
X_train

array([[-0.56320634, -0.33858826, -0.56197368, ..., -0.79907328,
         0.19452361, -0.75298811],
       [ 2.64669082,  1.73717104,  2.80948066, ...,  2.40906656,
         0.42875344,  0.16254587],
       [-0.14439938, -1.2245548 , -0.12317992, ..., -0.36896566,
         0.21967581, -0.15606649],
       ...,
       [-0.16161063, -1.50054962, -0.24414017, ..., -1.41681992,
        -1.03479003, -1.23716997],
       [-0.15013646, -1.11786773, -0.17031271, ...,  0.20826801,
         0.08133872, -0.65604281],
       [-0.83858626, -1.18512697, -0.84685594, ..., -1.15607479,
        -0.54903822, -0.78730021]])

In [7]:
X_test

array([[-2.96432044e-01, -1.76238373e-01, -3.72608310e-01, ...,
        -9.89910694e-01, -1.47495347e+00, -1.24969661e+00],
       [ 1.64270154e+00,  1.37768200e+00,  1.62073330e+00, ...,
         8.84499533e-01,  5.96958763e-01,  7.88828001e-04],
       [ 5.35299342e-02,  6.88854610e-01,  2.03412776e-01, ...,
         9.65220864e-01, -1.27738917e-01,  1.55572607e+00],
       ...,
       [-6.34919859e-01, -3.98889650e-01, -6.67501074e-01, ...,
        -3.61350443e-01,  2.76268250e-01, -7.93291208e-01],
       [-8.21375011e-01,  2.36337776e+00, -8.70630885e-01, ...,
        -1.75341264e+00, -2.13677066e+00, -1.39348064e+00],
       [ 2.31379464e-01, -5.82113097e-01,  2.96009938e-01, ...,
         1.33379751e+00,  1.03712221e+00,  1.19081961e+00]])

Label Encoding

In [8]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [10]:
y_train

array([0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,

In [9]:
y_test

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1])

Numpy array to pytorch tensor

In [10]:
x_train_tensor = torch.from_numpy(X_train)
x_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [11]:
x_train_tensor.shape
x_train_tensor

tensor([[-0.5632, -0.3386, -0.5620,  ..., -0.7991,  0.1945, -0.7530],
        [ 2.6467,  1.7372,  2.8095,  ...,  2.4091,  0.4288,  0.1625],
        [-0.1444, -1.2246, -0.1232,  ..., -0.3690,  0.2197, -0.1561],
        ...,
        [-0.1616, -1.5005, -0.2441,  ..., -1.4168, -1.0348, -1.2372],
        [-0.1501, -1.1179, -0.1703,  ...,  0.2083,  0.0813, -0.6560],
        [-0.8386, -1.1851, -0.8469,  ..., -1.1561, -0.5490, -0.7873]],
       dtype=torch.float64)

In [12]:
y_train_tensor.shape

torch.Size([426])

Defining the Model

In [13]:
class SimpleNN():
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1],1,dtype = torch.float64,requires_grad = True)
        self.bias = torch.zeros(1,dtype = torch.float64,requires_grad = True)
    
    def forward(self,X):
        z = torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self,y_pred,y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,epsilon, 1 - epsilon)

        # calculate loss using cross-entrophy
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss



        

Important Parameter which will require in Neural Network

In [14]:
learning_rate = 0.1
epochs = 25


Training Pipeline

In [15]:
# Create Model
model = SimpleNN(x_train_tensor)
# model.weights

# define loop
for epoch in range(epochs):
    # Forward Bias
    y_pred = model.forward(x_train_tensor)

    # loss calculate
    loss = model.loss_function(y_pred,y_train_tensor)
    print(f'Epoch: {epoch+1} loss:{loss.item()}')

    # backward pass
    loss.backward()

    # parameters update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad
    
    # Zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

Epoch: 1 loss:3.3826250741857344
Epoch: 2 loss:3.235507321578038
Epoch: 3 loss:3.084323600315575
Epoch: 4 loss:2.924249587201177
Epoch: 5 loss:2.7602350062429606
Epoch: 6 loss:2.5823943882251257
Epoch: 7 loss:2.401261108509328
Epoch: 8 loss:2.2150057428950642
Epoch: 9 loss:2.0306141307381274
Epoch: 10 loss:1.8516843009832853
Epoch: 11 loss:1.674865670773663
Epoch: 12 loss:1.5052089590231028
Epoch: 13 loss:1.3480736031703084
Epoch: 14 loss:1.2061998602319937
Epoch: 15 loss:1.0824695506653985
Epoch: 16 loss:0.979430336613758
Epoch: 17 loss:0.898529855941336
Epoch: 18 loss:0.8392513381036695
Epoch: 19 loss:0.7987343785961469
Epoch: 20 loss:0.7724812880748928
Epoch: 21 loss:0.7558247895210087
Epoch: 22 loss:0.7450584771047691
Epoch: 23 loss:0.7377156478331314
Epoch: 24 loss:0.732322512011064
Epoch: 25 loss:0.7280501955100416


In [21]:
model.bias

tensor([-0.1908], dtype=torch.float64, requires_grad=True)

Model Evaluation

In [24]:
with torch.no_grad():
    y_pred = model.forward(x_test_tensor)
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy : {accuracy.item()}")


Accuracy : 0.5944055914878845
